version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: apache-php
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - ./BrowserGame:/var/www/html/BrowserGame
      - ./NodeApp:/var/www/html/NodeApp
      # - ./PHPInit/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
volumes:
  db_data:
