version: '3.8'

services:
  apache-php:
    dockerfile: ./Dockerfile
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - ../BrowserGame/public/php:/usr/local/apache2/htdocs/
    depends_on:
      - db

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
volumes:
  db_data:
