name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Add SSH known hosts 
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOSTNAME }}
        run: |
          echo "Starting deployment..."
          ssh -v "${SSH_USER}@${SSH_HOST}" "
            sudo -i || exit 1;
            echo 'Changed to root user';
            cd /var/www/html || exit 1;
            echo 'Changed directory';
            git pull origin main || exit 1;
            echo 'Pull completed'
          "
          
