name: Deploy to EC2

on:
  push:
   branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCbheqcXONWaagZWIaophRHgZo5jEpGTpUPtbtYB6UbuwAAAMAgAF0HIABd
BwAAAAtzc2gtZWQyNTUxOQAAACCbheqcXONWaagZWIaophRHgZo5jEpGTpUPtbtYB6Ubuw
AAAECSt4xMOozLPLwe0oxDo3a+ar3i0qOiIyZ7HpJ8CkAT4JuF6pxc41ZpqBlYhqimFEeB
mjmMSkZOlQ+1u1gHpRu7AAAAN2VjMi11c2VyQGlwLTE3Mi0zMS0zLTE3LmFwLW5vcnRoZW
FzdC0xLmNvbXB1dGUuaW50ZXJuYWwBAgMEBQY=
-----END OPENSSH PRIVATE KEY----- }}

      -name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ 52.68.111.88 }} >> ~/.ssh/known_hosts

      -name: Deploy to EC2
        run: |
          ssh ${{ ec2-user }}@${{ 52.68.111.88 }} 
          ' cd /var/www/html && git pull origin main '
